'use client';
import React, {useEffect,useState,useRef} from 'react';
import {loadProgress, saveProgress,loadGrade,saveGrade} from './storage';
import {BookOpen,Compass,PenLine,Sun,ArrowRight,ArrowLeft,Volume2,Square,Check,Star,Leaf,Lightbulb,ShieldCheck,Clock,Flag,FolderHeart,Sparkles,GraduationCap,Coffee,Heart,ExternalLink} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './components/tabs';
import {Progress} from './components/progress';
import {lessons,units,emptyRecord,type RecordData} from './content';
import WOODLAND_IMAGE from './woodland.webp?inline';
import GradePicker from './grade-picker';
import {grades,gradeGuidance,stretchPrompts,type LearningGrade} from './grades';
const stages=['Word warm-up','Read & discover','Think it through','Create & share'];
const nav=[{id:'grades',label:'Grade explorer',icon:GraduationCap},{id:'day',label:'My day',icon:Sun},{id:'path',label:'My learning path',icon:Compass},{id:'library',label:'Reading library',icon:BookOpen},{id:'portfolio',label:'My creations',icon:FolderHeart}];
export default function Portal(){
 const [grade,setGrade]=useState<LearningGrade>('1');const [previewGrade,setPreviewGrade]=useState('1');const [gradeNotice,setGradeNotice]=useState('');
 const guidance=gradeGuidance[grade];
 const [week,setWeek]=useState(1);
 const [tab,setTab]=useState('day'); const [records,setRecords]=useState<Record<string,RecordData>>({});
 const [active,setActive]=useState<string|null>(null); const [record,setRecord]=useState<RecordData>(emptyRecord('beavers'));
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState('');
 const [hint,setHint]=useState(false); const [feedback,setFeedback]=useState('');const [speaking,setSpeaking]=useState(false);const [libraryId,setLibraryId]=useState('beavers');
 const statusRef=useRef({loading,error,active});statusRef.current={loading,error,active};const recordRef=useRef(record);recordRef.current=record;const recordsRef=useRef(records);recordsRef.current=records;
 const speechRef=useRef<SpeechSynthesisUtterance|null>(null);
 const lesson=lessons.find(l=>l.id===active)??lessons[0];
 const complete=Object.values(records).filter(r=>r.completed).length;
 const next=lessons.find(l=>!records[l.id]?.completed)??lessons[0];
 const unit=units.find(u=>u.week===week)!;
 const weekLessons=lessons.filter(l=>l.week===week);
 const nextWeekLessons=lessons.filter(l=>l.week===next.week);
 const activeUnit=units.find(u=>u.week===lesson.week)!;
 const weekPicker=<div className="week-picker" role="group" aria-label="Choose a week">{units.map(u=><button key={u.week} aria-pressed={week===u.week} onClick={()=>{setWeek(u.week);setLibraryId(lessons.find(l=>l.week===u.week)!.id);stop();setFeedback('')}}><small>WEEK {u.week}</small><strong>{u.title}</strong><span>{lessons.filter(l=>l.week===u.week&&records[l.id]?.completed).length}/4 complete</span></button>)}</div>;
 async function load(){setLoading(true);setError('');try{const data=loadProgress();setRecords(data);recordsRef.current=data;setWeek((lessons.find(l=>!data[l.id]?.completed)??lessons[0]).week);setLibraryId((lessons.find(l=>!data[l.id]?.completed)??lessons[0]).id)}catch(e:any){setError(e.message||'Your saved work could not be opened. Please try again.')}finally{setLoading(false)}}
 useEffect(()=>{const g=loadGrade();setGrade(g);setPreviewGrade(g);load();return()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel()}},[]);
 useEffect(()=>{const dirty=active&&record.draft!==(records[active]?.draft??'');const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[record.draft,records,active]);
 function chooseGrade(g:LearningGrade){setGrade(g);setPreviewGrade(g);setGradeNotice('');try{saveGrade(g)}catch(e:any){setGradeNotice(e.message)}setTab('path');window.scrollTo({top:0,behavior:'smooth'})}
 async function openGrades(){if(active&&!await leave())return;setPreviewGrade(grade);setTab('grades');stop();window.scrollTo({top:0,behavior:'smooth'})}
 function stop(){if('speechSynthesis'in window)window.speechSynthesis.cancel();setSpeaking(false)}
 function read(text:string){if(!('speechSynthesis'in window)){setFeedback('Audio is unavailable in this browser. You can read the words here or ask a grown-up to read with you.');return}stop();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.84;u.onend=()=>setSpeaking(false);u.onerror=()=>{setSpeaking(false);setFeedback('Audio could not play. You can read here or try again.')};speechRef.current=u;window.speechSynthesis.speak(u);setSpeaking(true)}
 async function persist(data:RecordData){if(busy)return false;setBusy(true);setSaved('');setError('');try{const updated={...data,updatedAt:new Date().toISOString()};const all=saveProgress(updated);recordsRef.current=all;setRecords(all);setSaved('Saved on this device');return true}catch(e:any){setError(e.message||'Not saved yet. Keep this page open and try again.');return false}finally{setBusy(false)}}
 function start(id:string){const s=statusRef.current;if(s.loading){setError('Please wait for your progress to load.');return}if(s.error&&!s.active){setError('Please reload saved progress before starting a lesson.');return;}stop();const r=recordsRef.current[id]??emptyRecord(id);setRecord(r);setActive(id);setHint(false);setFeedback('');setSaved('');window.scrollTo({top:0,behavior:'smooth'})}
 async function leave(){if(busy)return false;if(record.draft!==(records[record.lessonId]?.draft??'')||record.step!==(records[record.lessonId]?.step??0)){if(!await persist(record))return false}stop();setActive(null);setFeedback('');setError('');return true}
 async function go(step:number){const p={...record,step};if(await persist(p)){setRecord(p);setHint(false);setFeedback('');stop();window.scrollTo({top:0,behavior:'smooth'})}}
 async function answer(key:string,choice:number){const prev=record.answers[key];const a={choice,attempts:(prev?.attempts??0)+1,hinted:hint||!!prev?.hinted};const p={...record,completed:false,answers:{...record.answers,[key]:a}};setRecord(p);const correct=choice===(key==='word'?lesson.wordAnswer:lesson.answer);setFeedback(correct?(key==='word'?'You found it! Say the word once more.':lesson.explanation):'Take another look. Use a hint, then try a different answer.');await persist(p)}
 async function finish(){const p={...record,step:4,completed:true};if(await persist(p)){setRecord(p);stop();setFeedback('')}}
 useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(c.registerTool({name:'get_learning_progress',description:'Read saved lesson progress for this learner without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');return {lessons:lessons.map(l=>({id:l.id,title:l.title,step:recordsRef.current[l.id]?.step??0,completed:!!recordsRef.current[l.id]?.completed}))}}},{signal:lifecycle.signal})).catch(()=>{});Promise.resolve(c.registerTool({name:'start_lesson',description:'Open or resume a literacy lesson. Does not complete or score any activity.',inputSchema:{type:'object',properties:{lessonId:{type:'string',enum:lessons.map(l=>l.id)}},required:['lessonId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||!lessons.some(l=>l.id===input.lessonId)||Object.keys(input).some(k=>k!=='lessonId'))throw Error('Choose a valid lessonId');if(recordRef.current.draft!==(recordsRef.current[recordRef.current.lessonId]?.draft??''))throw Error('Save the current writing before opening another lesson');start(input.lessonId);return {opened:input.lessonId}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const audioButton=(text:string)=><button className="text-button" onClick={()=>speaking?stop():read(text)}>{speaking?<Square size={17}/>:<Volume2 size={18}/>} {speaking?'Stop audio':'Listen'}</button>;
 const progressBar=<Progress value={complete/lessons.length*100} aria-label={`${complete} of ${lessons.length} lessons complete`}/>;
 return <div className="app-shell">
 <a className="skip" href="#main">Skip to learning</a>
 <header className="site-header"><button className="brand" onClick={()=>active?leave():setTab('day')} aria-label="Literacy Quest home"><span className="brand-mark"><BookOpen size={25}/></span><span>literacy<span className="brand-light">quest</span><span className="brand-star">✦</span></span></button><div className="header-right"><button className="grade-switch" onClick={openGrades} aria-label={`Change grade guide, currently Grade ${grade}`}><GraduationCap size={16}/><span>Grade {grade}</span></button><button className={`parent-button ${tab==='parent'?'selected':''}`} onClick={async()=>{if(active&&!await leave())return;setTab('parent')}}><ShieldCheck size={17}/> For grown-ups</button><span className="avatar" aria-label="Explorer profile">E</span></div></header>
 {error&&<div className="notice error" role="alert">{error} <button onClick={()=>active?persist(record):load()} disabled={busy}>Try again</button></div>}

 {gradeNotice&&<p className="notice" role="status">{gradeNotice}</p>}
 {!active?<Tabs value={tab} onValueChange={v=>{setTab(v);stop();setFeedback('')}}><div className="nav-wrap"><TabsList className="main-nav" aria-label="Learning areas">{nav.map(n=><TabsTrigger key={n.id} value={n.id}><n.icon size={18}/>{n.label}</TabsTrigger>)}<TabsTrigger value="parent" className="sr-only">For grown-ups</TabsTrigger></TabsList><span className="nav-note">A little discovery, every day.</span></div><main id="main" className="main-container">
 <TabsContent value="grades"><GradePicker preview={previewGrade} onPreview={setPreviewGrade} current={grade} onChoose={chooseGrade}/></TabsContent>
 <TabsContent value="day"><div className="page-heading"><div><p className="eyebrow">LET’S KEEP GROWING</p><h1>Hello, explorer<span className="gold">!</span></h1><p>A new discovery is waiting for you.</p></div><span className="unit-label"><Leaf size={17}/> 4 weeks · 16 discoveries</span></div>
 <div className="guide-banner"><div><GraduationCap size={23}/><span><strong>Grade {grade} · {guidance.label}</strong><small>Your guide for this shared 16-lesson adventure.</small></span></div><button className="text-button" onClick={openGrades}>Explore K–5<ArrowRight size={17}/></button></div>
 <div className="dashboard-grid"><section className="hero-card"><div className="hero-copy"><span className="label-badge">YOUR FOUR-WEEK ADVENTURE</span><h2>Small steps.<br/>A world to discover.</h2><p>Explore animals, gardens, neighbors, and weather. Read, wonder, and create.</p><div className="hero-meta"><span><Clock size={16}/> About 20 min</span><span><Flag size={16}/> 4 activities</span></div><button className="primary" disabled={loading} onClick={()=>start(next.id)}>{loading?'Loading your progress…':complete===lessons.length?'Explore again':records[next.id]?'Continue my adventure':'Start my adventure'}<ArrowRight size={18}/></button><small>{complete===lessons.length?'Your four-week adventure is complete!':`Week ${next.week} · Up next: ${next.title}`}</small></div><div className="hero-art"><img src={WOODLAND_IMAGE} alt="Storybook illustration of a friendly beaver beside a woodland pond"/><span className="art-caption">READ · DISCOVER · CREATE</span></div></section>
 <aside className="journey-card"><div className="row"><span className="icon-box yellow"><Star size={21}/></span><span className="eyebrow">YOUR JOURNEY</span></div><h3>Little steps.<br/>Big discoveries.</h3><div className="progress-numbers"><strong>{complete}<span> / {lessons.length}</span></strong><span>lessons complete</span></div>{progressBar}<p className="journey-week">Week {next.week} · {units.find(u=>u.week===next.week)!.title}</p><div className="journey-list">{nextWeekLessons.map((l,i)=><button key={l.id} onClick={()=>start(l.id)}><span className={`step-dot ${records[l.id]?.completed?'done':''}`}>{records[l.id]?.completed?<Check size={13}/>:i+1}</span><span>{l.label}</span>{l.id===next.id&&<span className="tiny-next">NEXT</span>}</button>)}</div><p className="gentle">Your pace. Your adventure.</p></aside></div>
 <div className="section-heading"><h2>A little of each, every day</h2><span>READ · DISCOVER · CREATE</span></div><div className="activity-grid">{[{icon:Sparkles,title:'Play with words',text:'Build confidence, one sound at a time.',color:'green',cta:'Explore my path',to:'path'},{icon:BookOpen,title:'Find your next story',text:'Get curious about the world around you.',color:'blue',cta:'Open the library',to:'library'},{icon:PenLine,title:'Let your ideas grow',text:'Turn your discoveries into your own words.',color:'amber',cta:'See my creations',to:'portfolio'}].map(x=><button key={x.to} className={`activity-card ${x.color}`} onClick={()=>setTab(x.to)}><span className={`icon-box ${x.color}`}><x.icon size={23}/></span><h3>{x.title}</h3><p>{x.text}</p><span className="card-link">{x.cta}<ArrowRight size={17}/></span></button>)}</div><div className="family-tip"><Lightbulb size={22}/><div><strong>Take your learning off screen</strong><span>Look outside with a grown-up. Can you spot a place an animal might call home?</span></div></div>
 </TabsContent>
 <TabsContent value="path"><div className="page-heading"><div><p className="eyebrow">ONE DISCOVERY AT A TIME</p><h1>My learning path</h1><p>Four weeks, four lessons each. Follow the suggested order or choose your own pace.</p></div></div><div className="guide-banner"><div><GraduationCap size={23}/><span><strong>Grade {grade} · {guidance.label}</strong><small>{grade==='1'?'Read together, say your idea, then write.':'Read closely, explain your answer, then extend your writing.'}</small></span></div><button className="text-button" onClick={openGrades}>Change guide<ArrowRight size={17}/></button></div><div className="course-overview"><span>{complete} of {lessons.length} lessons complete</span>{progressBar}</div>{weekPicker}<div className="unit-banner"><Leaf/><div><h2>Week {week}: {unit.title}</h2><p>{unit.goal}</p></div><span>{weekLessons.filter(l=>records[l.id]?.completed).length} of 4 complete</span></div><div className="path-list">{weekLessons.map((l,i)=><article className="path-card" key={l.id}><span className={`path-number ${records[l.id]?.completed?'done':''}`}>{records[l.id]?.completed?<Check/>:`0${i+1}`}</span><div><p className="eyebrow">DAY {i+1} · {l.focus}</p><h2>{l.title}</h2><p>{l.subtitle}</p></div><button className="primary" onClick={()=>start(l.id)}>{records[l.id]?.completed?'Revisit':records[l.id]?'Continue':'Begin'}<ArrowRight size={17}/></button></article>)}</div><div className="weekly-project"><PenLine size={23}/><div><h3>This week’s creation</h3><p>{unit.project}</p><small>Complete it in Day 4, then share your writing with a grown-up.</small></div></div><p className="muted small">Suggested rhythm: one lesson a day, four days a week. Each lesson takes about 15–20 minutes. Take longer whenever you need.</p></TabsContent>
 <TabsContent value="library"><div className="page-heading"><div><p className="eyebrow">A WORLD TO DISCOVER</p><h1>Reading library</h1><p>Read a little. Wonder a lot.</p></div></div>{weekPicker}<div className="library-layout"><div className="book-list">{weekLessons.map((l,i)=><button key={l.id} className={`book-item ${libraryId===l.id?'selected':''}`} onClick={()=>{setLibraryId(l.id);stop()}}><span className={`book-spine ${l.color}`}><BookOpen/></span><span><small>WEEK {l.week} · DAY {i+1}</small><strong>{l.title}</strong><span>{l.subtitle}</span></span></button>)}</div><article className="reading-paper"><span className="eyebrow">READ TO DISCOVER · {lessons.find(l=>l.id===libraryId)!.genre.toUpperCase()}</span><h2>{lessons.find(l=>l.id===libraryId)!.title}</h2>{audioButton(lessons.find(l=>l.id===libraryId)!.text.join(' '))}{lessons.find(l=>l.id===libraryId)!.text.map((p,i)=><p className="story-paragraph" key={i}>{p}</p>)}<button className="primary" onClick={()=>start(libraryId)}>Try the activities<ArrowRight size={18}/></button><p role="status" className="small">{feedback}</p><p className="muted small">Read on your own, listen, or read with a grown-up. Library reading does not change lesson completion.</p></article></div></TabsContent>
 <TabsContent value="portfolio"><div className="page-heading"><div><p className="eyebrow">MADE BY YOU</p><h1>My creations</h1><p>Your ideas deserve a place to shine.</p></div></div>{Object.values(records).some(r=>r.draft)?<div className="creations-grid">{lessons.filter(l=>records[l.id]?.draft).map(l=><article key={l.id} className="creation"><span className="label-badge">{records[l.id].completed?'FINISHED PIECE':'WORK IN PROGRESS'}</span><h2>{l.title}</h2><p className="writing-preview">{records[l.id].draft}</p><button className="text-button" onClick={()=>{start(l.id);setRecord({...records[l.id],step:3})}}>Open my writing<PenLine size={17}/></button></article>)}</div>:<section className="empty-state"><span className="icon-box amber"><PenLine size={32}/></span><h2>Your first creation starts with a discovery.</h2><p>Finish the writing activity in a lesson. Your words will appear here.</p><button className="primary" onClick={()=>start(next.id)}>Make my first creation<ArrowRight size={18}/></button></section>}</TabsContent>
 <TabsContent value="parent"><div className="page-heading"><div><p className="eyebrow">A WINDOW INTO THEIR LEARNING</p><h1>For grown-ups</h1><p>Small moments of support make room for discovery.</p></div><button className="text-button" onClick={()=>setTab('day')}>Back to learning<ArrowRight size={17}/></button></div><div className="parent-summary"><article><strong>{complete}/{lessons.length}</strong><span>Lessons completed</span></article><article><strong>{Object.values(records).filter(r=>r.draft.trim()).length}</strong><span>Writing pieces saved</span></article><article><strong>{Object.values(records).flatMap(r=>Object.values(r.answers)).filter(a=>a.hinted||a.attempts>1).length}</strong><span>Questions with support</span></article></div>{weekPicker}<div className="parent-grid"><section className="panel"><h2>Week {week} learning snapshots</h2>{weekLessons.map(l=>{const r=records[l.id];return <div className="snapshot" key={l.id}><div><strong>{l.title}</strong><small>{l.focus}</small></div><span>{r?.completed?'Completed':r?'In progress':'Not started'}</span>{r&&<p>{Object.entries(r.answers).map(([k,a])=>`${k==='word'?'Word practice':'Comprehension'}: ${a.hinted||a.attempts>1?'with support':'first attempt'}`).join(' · ')||'Reading and exploration in progress.'}</p>}</div>})}</section><section className="panel"><h2>Try this together</h2><p>{unit.family}</p><h3>Grade {grade} guide: {guidance.label}</h3><p>{guidance.read} {guidance.write}</p><button className="text-button" onClick={openGrades}>View K–5 goals<ArrowRight size={17}/></button><h3>About this four-week course</h3><p>Sixteen original lessons for grades 1–2, organized into four weeks of home enrichment. Word practice assumes some prior letter–sound knowledge. Read the informational texts aloud when needed.</p><p>These short activities show practice, not a diagnostic reading level or proof of mastery. Writing is saved for you to review; it is not automatically graded.</p><p className="muted small">One learner workspace per browser on this device. Progress and writing are saved in this browser, with no sign-in. They do not sync to other devices and can be lost if browsing data is cleared. The family view is not a separate protected login.</p></section></div></TabsContent>
 </main></Tabs>:<main id="main" className="lesson-container"><div className="lesson-top"><button className="text-button" onClick={leave} disabled={busy}><ArrowLeft size={18}/> Save & back</button><span className="eyebrow">WEEK {lesson.week} · {activeUnit.title.toUpperCase()} · DAY {lessons.filter(l=>l.week===lesson.week).findIndex(l=>l.id===active)+1}</span><span className="save-status" role="status">{busy?'Saving…':saved}</span></div>
 {record.step===4?<section className="celebration"><span className="award"><Star size={44}/></span><p className="eyebrow">ANOTHER DISCOVERY IS YOURS</p><h1>You did it, explorer!</h1><p>You practiced words, read {lesson.title}, and shared your ideas.</p><div className="finished-writing"><h3>In your own words</h3><p>{record.draft}</p></div><div className="actions"><button className="secondary" onClick={()=>{setActive(null);setTab('portfolio')}}>See my creations</button><button className="primary" onClick={()=>{setWeek(lesson.week);setLibraryId(lesson.id);setActive(null);setTab('path')}}>My next discovery<ArrowRight size={18}/></button></div><p className="muted">{lesson.talk}</p></section>:<><div className="lesson-title"><p className="eyebrow">{lesson.subtitle}</p><h1>{lesson.title}</h1></div><div className="stage-row">{stages.map((s,i)=><span key={s} className={i===record.step?'current':i<record.step?'past':''}><b>{i<record.step?<Check size={15}/>:i+1}</b>{s}</span>)}</div><Progress value={record.step/4*100} aria-label={`Activity ${record.step+1} of 4`}/><section className="lesson-panel" key={`${active}-${record.step}`}>
 {record.step===0&&<><span className="label-badge">WORD WARM-UP</span><h2>{lesson.pattern}</h2><p className="instruction">{lesson.model}</p><p className="grade-coach"><strong>Grade {grade} guide</strong>{guidance.word}</p>{audioButton(lesson.words.join('. '))}<div className="word-tiles">{lesson.words.map(w=><button key={w} onClick={()=>read(w)}>{w}<Volume2 size={17}/></button>)}</div><h3>{lesson.wordQuestion}</h3><div className="answer-options">{lesson.wordOptions.map((o,i)=><button key={o} disabled={busy} className={record.answers.word?.choice===i?'chosen':''} onClick={()=>answer('word',i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div><button className="text-button" onClick={()=>setHint(true)}><Lightbulb size={17}/>Give me a hint</button>{hint&&<p className="hint">{lesson.wordHint}</p>}</>}
 {record.step===1&&<><div className="row spread"><span className="label-badge">READ & DISCOVER · {lesson.genre.toUpperCase()}</span>{audioButton(lesson.text.join(' '))}</div><h2>{lesson.title}</h2><p className="grade-coach"><strong>Grade {grade} guide</strong>{guidance.read}</p>{lesson.text.map((p,i)=><p key={i} className="story-paragraph">{p}</p>)}<div className="vocab"><BookOpen size={22}/><p><strong>{lesson.vocab}</strong><span>{lesson.definition}</span></p></div></>}
 {record.step===2&&<><span className="label-badge">THINK IT THROUGH</span><h2>{lesson.question}</h2><p className="grade-coach"><strong>Grade {grade} guide</strong>{guidance.meaning}</p><details><summary>Look back at the text</summary>{lesson.text.map((p,i)=><p key={i}>{p}</p>)}</details><div className="answer-options">{lesson.options.map((o,i)=><button key={o} disabled={busy} className={record.answers.meaning?.choice===i?'chosen':''} onClick={()=>answer('meaning',i)}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div><button className="text-button" onClick={()=>setHint(true)}><Lightbulb size={17}/>Give me a hint</button>{hint&&<p className="hint">{lesson.hint}</p>}</>}
 {record.step===3&&<><span className="label-badge">CREATE & SHARE</span><h2>Now it’s your story to tell.</h2><p className="instruction">{lesson.prompt}</p><p className="grade-coach"><strong>Grade {grade} guide</strong>{guidance.write}</p>{grade==='2'&&<div className="stretch-prompt"><strong>Try a little more · optional</strong><p>{stretchPrompts[lesson.id]}</p><small>Use the writing box below. A grown-up can help review your ideas.</small></div>}<div className="hint"><strong>Need a starting point?</strong><p>{lesson.frame}</p></div><label htmlFor="writing">Write in your own words. Use the starting point if you need help.</label><textarea id="writing" maxLength={4000} rows={6} value={record.draft} onChange={e=>{setSaved('Unsaved writing');setRecord({...record,completed:false,draft:e.target.value})}} placeholder="I discovered that…"/><div className="row spread"><span className="muted small">{record.draft.trim()?record.draft.trim().split(/\s+/).length:0} words · saved when you choose Save</span><button className="text-button" disabled={busy} onClick={()=>persist(record)}>Save my writing<Check size={17}/></button></div><div className="talk-together"><Volume2 size={21}/><div><strong>Talk & listen together</strong><p>{lesson.talk}</p></div></div><div className="writing-check"><h3>Before you finish, check:</h3><p>Did I share an idea from the text? Did I start each sentence with a capital letter and end with punctuation?</p></div></>}
 {feedback&&<p role="status" className="feedback">{feedback}</p>}
 <div className="lesson-actions"><button className="text-button" disabled={record.step===0||busy} onClick={()=>go(record.step-1)}><ArrowLeft size={17}/>Back</button>{record.step<3?<button className="primary" disabled={busy||(record.step===0&&record.answers.word?.choice!==lesson.wordAnswer)||(record.step===2&&record.answers.meaning?.choice!==lesson.answer)} onClick={()=>go(record.step+1)}>{record.step===1?'I’m ready to think':'Keep going'}<ArrowRight size={18}/></button>:<button className="primary" disabled={busy||record.draft.trim().split(/\s+/).length<6} onClick={finish}>Finish my adventure<Check size={18}/></button>}</div>{record.step===3&&<p className="small muted">Write at least six words to save a finished piece. A grown-up can help you review it.</p>}
 </section></>}
 </main>}
 {!active&&tab==='day'&&<section className="support-section" aria-labelledby="support-title"><div className="support-card"><div className="support-symbol" aria-hidden="true"><Coffee size={105} strokeWidth={1.25}/><Heart size={24} className="coffee-heart"/></div><div className="support-copy"><p className="support-kicker">FOR PARENTS & EDUCATORS</p><h2 id="support-title">Help little readers grow.</h2><p>Literacy Quest is free to explore, with no accounts or ads. If it has helped your family, you can thank the creator with a coffee.</p><a className="coffee-button" href="https://buymeacoffee.com/henryyu" target="_blank" rel="noopener noreferrer" aria-label="Buy Me a Coffee — opens in a new tab"><Coffee size={24}/>Buy Me a Coffee<ExternalLink size={17}/></a><p className="creator-credit">Created by Dr. Henry Yu · Thank you for your support.</p></div></div></section>}
 <footer className="site-footer"><span><BookOpen size={15}/> Literacy Quest</span><span>K–5 goals · Grade 1–2 adventures available now.</span><a href="https://buymeacoffee.com/henryyu" target="_blank" rel="noopener noreferrer" className="footer-coffee"><Coffee size={16}/> Buy Me a Coffee</a></footer>
 </div>
}
