// Run with Node after installing the development dependencies in source/.
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('node:crypto').webcrypto;
const ts=require('typescript');
const root=__dirname;
function moduleFrom(file,req,win){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(root+'/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:req,window:win,crypto,TextEncoder});return exports}
const content=moduleFrom('content.ts');const {lessons}=content;
function setup(){const map=new Map();let blocked=false;const win={location:{pathname:'/literacyquest/'},localStorage:{getItem:k=>map.get(k)??null,setItem:(k,v)=>{if(blocked)throw Error('quota');map.set(k,v)}}};const store=moduleFrom('storage.ts',()=>content,win);return{store,map,win,block:()=>blocked=true}}
const {store,map,win,block}=setup();const l=lessons[0];const old={lessonId:l.id,step:4,answers:{word:{choice:l.wordAnswer,attempts:1,hinted:false},meaning:{choice:l.answer,attempts:1,hinted:false}},draft:'A beaver builds a lodge with sticks and mud.',completed:true};
map.set(store.storageKey(),JSON.stringify({version:1,records:{[l.id]:old}}));map.set(store.storageKey()+':grade-guide','2');const legacy=map.get(store.storageKey());
let w=store.loadWorkspace();assert.equal(w.profiles[0].grade,'2');assert.equal(w.profiles[0].records[l.id].draft,old.draft);assert.equal(map.has(store.workspaceKey()),false);
w=store.addProfile('River','1');const river=w.activeId;assert.equal(w.profiles.length,2);assert.equal(Object.keys(store.loadProgress(river)).length,0);assert.equal(map.get(store.storageKey()),legacy);
store.saveProgress({...old,draft:'River writes about a beaver home in the pond.'},river);assert.equal(store.loadProgress('original')[l.id].draft,old.draft);
store.saveGrade('1','original');assert.equal(store.loadGrade('original'),'1');assert.equal(store.loadGrade(river),'1');store.saveGrade('2',river);assert.equal(store.loadGrade('original'),'1');
store.selectProfile('original');store.saveProgress({...old,completed:false,step:3,draft:'An unfinished writing piece by River.'},river);assert.equal(store.loadWorkspace().activeId,'original');assert.equal(store.loadProgress('original')[l.id].completed,true);
const backup=store.createBackup(), serialized=JSON.stringify(backup);const parsed=store.parseBackup(serialized);assert.equal(parsed.profiles.length,2);
const before=JSON.stringify(store.loadWorkspace().profiles);w=store.restoreBackup(parsed);assert.equal(w.profiles.length,4);assert.equal(JSON.stringify(w.profiles.slice(0,2)),before);assert.equal(new Set(w.profiles.map(p=>p.id)).size,4);assert(w.profiles[2].name.endsWith('(restored)'));assert.equal(w.profiles[3].records[l.id].draft,'An unfinished writing piece by River.');
const other=setup();const otherW=other.store.restoreBackup(parsed);assert.equal(otherW.profiles.length,2);assert.equal(otherW.profiles[0].records[l.id].completed,true);
const snapshots=()=>JSON.stringify([...map.entries()]);let untouched=snapshots();
for(const invalid of ['not json','{}',JSON.stringify({...backup,version:9}),JSON.stringify({...backup,profiles:[{name:'Bad',grade:'6',records:{}}]}),JSON.stringify({...backup,profiles:[{name:'Bad',grade:'1',records:{unknown:old}}]}),JSON.stringify({...backup,profiles:[{name:'Bad',grade:'1',records:{beavers:{...old,draft:'short'}}}]}),'x'.repeat(store.MAX_BACKUP_BYTES+1)]){assert.throws(()=>store.parseBackup(invalid));assert.equal(snapshots(),untouched)}
assert.throws(()=>store.addProfile('  ','1'));assert.throws(()=>store.selectProfile('unknown'));assert.throws(()=>store.saveGrade('6','original'));assert.equal(snapshots(),untouched);
store.renameProfile(river,'<script>alert(1)</script>');assert.equal(store.loadWorkspace().profiles.find(p=>p.id===river).name,'<script>alert(1)</script>'); // React renders text, never HTML.
untouched=snapshots();block();assert.throws(()=>store.addProfile('Quota','1'));assert.throws(()=>store.restoreBackup(parsed));assert.throws(()=>store.saveProgress({...old,draft:'Changed words must never replace saved work on failure.'},'original'));assert.equal(snapshots(),untouched);
win.location.pathname='/literacyquest/index.html';assert.equal(store.storageKey(),'literacy-quest-html:v1:/literacyquest/');
const corrupt=setup();corrupt.map.set(corrupt.store.storageKey(),'{bad');assert.throws(()=>corrupt.store.loadWorkspace());assert.equal(corrupt.map.size,1);
const capped=setup();for(let i=1;i<20;i++)capped.store.addProfile('Learner '+i,'1');const capBefore=JSON.stringify([...capped.map.entries()]);assert.throws(()=>capped.store.restoreBackup(parsed));assert.throws(()=>capped.store.addProfile('One too many','1'));assert.equal(JSON.stringify([...capped.map.entries()]),capBefore);
console.log('PASS: legacy import, separate learners/grades, explicit learner save, backup round trip on another device, additive restore, invalid/oversized input rejection, quota/corruption safety, limits, stable URL key.');

const fullBackup=capped.store.createBackup();const cleanDevice=setup();assert.equal(cleanDevice.store.restoreBackup(fullBackup).profiles.length,20);console.log('PASS: full 20-learner backup restores on a fresh device.');

const kenv=setup();let kw=kenv.store.addProfile('Little Fox','K');const kid=kw.activeId;
const klesson=content.kindergartenLessons[0];const krecord={lessonId:klesson.id,step:4,answers:{word:{choice:klesson.wordAnswer,attempts:1,hinted:false},meaning:{choice:klesson.answer,attempts:1,hinted:false}},draft:'hat',completed:true};
assert(kenv.store.validateRecord(krecord));assert(!kenv.store.validateRecord({...krecord,draft:'  '}));assert(!kenv.store.validateRecord({...old,draft:'hat'}));
kenv.store.saveProgress(krecord,kid);kenv.store.saveProgress(old,kid);kenv.store.saveGrade('1',kid);
assert.equal(content.courseLessons('K').filter(l=>kenv.store.loadProgress(kid)[l.id]?.completed).length,1);
assert.equal(content.courseLessons('1').filter(l=>kenv.store.loadProgress(kid)[l.id]?.completed).length,1);
assert.equal(kenv.store.loadProgress(kid)[klesson.id].draft,'hat');
kenv.store.saveGrade('K',kid);const kb=kenv.store.createBackup();const kr=setup().store.restoreBackup(kb);assert.equal(kr.profiles[1].grade,'K');assert.equal(Object.keys(kr.profiles[1].records).length,2);
assert.equal(lessons.length,80);assert.equal(new Set(lessons.map(l=>l.id)).size,80);
for(const g of ['K','1','2','3','4','5']){assert.equal(content.courseLessons(g).length,16);for(let week=1;week<=4;week++)assert.equal(content.courseLessons(g).filter(l=>l.week===week).length,4)}
for(const l of content.kindergartenLessons){assert.equal(l.wordOptions.length,3);assert.equal(l.options.length,3);assert(l.wordAnswer>=0&&l.wordAnswer<3);assert(l.answer>=0&&l.answer<3);assert.equal(l.text.length,3);assert(content.minimumWords(l.id)===1);}
console.log('PASS: 16 K lessons, distinct course progress, K one-word completion, blank rejection, older six-word rule, mixed-course backup restore.');

const g3env=setup();let g3w=g3env.store.addProfile('Story Detective','3');const detective=g3w.activeId;
const g3lesson=content.gradeThreeLessons[0];const g3record={lessonId:g3lesson.id,step:4,answers:{word:{choice:g3lesson.wordAnswer,attempts:1,hinted:false},meaning:{choice:g3lesson.answer,attempts:1,hinted:false},evidence:{choice:g3lesson.evidenceAnswer,attempts:2,hinted:true}},draft:'Maya and Eli keep careful notes about the holes they can see. They leave a question mark because they have not seen an animal making them.',completed:true};
assert(g3env.store.validateRecord(g3record));assert(!g3env.store.validateRecord({...g3record,draft:'This response is still much too short.'}));
const missing=structuredClone(g3record);delete missing.answers.evidence;assert(!g3env.store.validateRecord(missing));
assert(!g3env.store.validateRecord({...g3record,answers:{...g3record.answers,evidence:{choice:(g3lesson.evidenceAnswer+1)%3,attempts:1,hinted:false}}}));
assert(!g3env.store.validateRecord({...old,answers:{...old.answers,evidence:g3record.answers.evidence}}));
g3env.store.saveProgress(g3record,detective);g3env.store.saveProgress(krecord,detective);g3env.store.saveProgress(old,detective);
for(const grade of ['K','1','2','3']){g3env.store.saveGrade(grade,detective);assert.equal(g3env.store.loadGrade(detective),grade);assert.equal(content.courseLessons(grade).filter(l=>g3env.store.loadProgress(detective)[l.id]?.completed).length,1)}
const g3backup=g3env.store.createBackup();const g3restored=setup().store.restoreBackup(g3backup);const restoredDetective=g3restored.profiles.find(p=>p.grade==='3');assert(restoredDetective);assert.equal(Object.keys(restoredDetective.records).length,3);assert.equal(restoredDetective.records[g3lesson.id].answers.evidence.attempts,2);assert.equal(restoredDetective.records[g3lesson.id].draft,g3record.draft);
for(const l of content.gradeThreeLessons){assert.equal(l.text.length,3);assert(content.wordCount(l.text.join(' '))>=100);assert.equal(l.wordOptions.length,3);assert.equal(l.options.length,3);assert.equal(l.evidenceOptions.length,3);for(const a of [l.wordAnswer,l.answer,l.evidenceAnswer])assert(Number.isInteger(a)&&a>=0&&a<=2);assert(content.minimumWords(l.id)===20);assert.equal(content.evidenceFor(l.id).id,l.id);assert(g3env.store.validateRecord({...g3record,lessonId:l.id,answers:{word:{choice:l.wordAnswer,attempts:1,hinted:false},meaning:{choice:l.answer,attempts:1,hinted:false},evidence:{choice:l.evidenceAnswer,attempts:1,hinted:false}}}))}
assert.equal(content.minimumWords('beavers'),6);assert.equal(content.minimumWords('k-rhyme'),1);
console.log('PASS: 16 Grade 3 lessons; evidence required and validated; 20-word participation threshold; K/1/2 rules preserved; mixed-course progress and evidence backup round trip.');

const g4env=setup();const g4profile=g4env.store.addProfile('Evidence Explorer','4').activeId;
const g4lesson=content.gradeFourLessons[0];const g4record={lessonId:g4lesson.id,step:4,completed:true,draft:'Lena values accurate information because she stops to check the mill location instead of guessing. She asks another volunteer to help and then shares the correct answer with the visitor.\n\nLater, she adds a label to her notes and checks another unfamiliar street. These actions suggest that she cares about learning and giving reliable directions.',answers:{word:{choice:g4lesson.wordAnswer,attempts:1,hinted:false},meaning:{choice:g4lesson.answer,attempts:1,hinted:false},evidence:{choice:g4lesson.evidenceAnswer,attempts:2,hinted:true},reasoning:{choice:g4lesson.reasoningAnswer,attempts:2,hinted:true}}};
assert(g4env.store.validateRecord(g4record));
const missingReason=structuredClone(g4record);delete missingReason.answers.reasoning;assert(!g4env.store.validateRecord(missingReason));assert(!g4env.store.validateRecord({...missingReason,completed:false}));
const wrongReason=structuredClone(g4record);wrongReason.answers.reasoning.choice=(g4lesson.reasoningAnswer+1)%3;assert(!g4env.store.validateRecord(wrongReason));
const missingEvidence=structuredClone(g4record);delete missingEvidence.answers.evidence;assert(!g4env.store.validateRecord(missingEvidence));
assert(!g4env.store.validateRecord({...g4record,draft:Array(39).fill('word').join(' ')}));assert(g4env.store.validateRecord({...g4record,draft:Array(40).fill('word').join(' ')})); // Participation only; not an automated quality score.
assert(g4env.store.validateRecord({...missingReason,step:2,completed:false,draft:''}));
assert(!g4env.store.validateRecord({...g3record,answers:{...g3record.answers,reasoning:g4record.answers.reasoning}}));
for(const record of [old,krecord,g3record,g4record])g4env.store.saveProgress(record,g4profile);
for(const grade of ['K','1','2','3','4']){g4env.store.saveGrade(grade,g4profile);assert.equal(content.courseLessons(grade).filter(l=>g4env.store.loadProgress(g4profile)[l.id]?.completed).length,1)}
const g4backup=g4env.store.createBackup();const g4target=setup();const g4restored=g4target.store.restoreBackup(g4backup).profiles.find(p=>p.grade==='4');assert(g4restored);assert.equal(Object.keys(g4restored.records).length,4);assert.equal(g4restored.records[g4lesson.id].answers.reasoning.attempts,2);assert.equal(g4restored.records[g4lesson.id].draft,g4record.draft);
const mixedBackup=g4target.store.parseBackup(JSON.stringify(g4target.store.createBackup()));assert.equal(mixedBackup.profiles.length,2);
const tampered=structuredClone(g4backup);delete tampered.profiles.find(p=>p.grade==='4').records[g4lesson.id].answers.reasoning;const safeBefore=JSON.stringify(g4target.store.loadWorkspace());assert.throws(()=>g4target.store.restoreBackup(tampered));assert.equal(JSON.stringify(g4target.store.loadWorkspace()),safeBefore);
for(const l of content.gradeFourLessons){assert.equal(l.text.length,4);assert(content.wordCount(l.text.join(' '))>=180);for(const options of [l.wordOptions,l.options,l.evidenceOptions,l.reasoningOptions])assert.equal(options.length,3);for(const a of [l.wordAnswer,l.answer,l.evidenceAnswer,l.reasoningAnswer])assert(Number.isInteger(a)&&a>=0&&a<=2);assert.equal(content.minimumWords(l.id),40);assert.equal(content.reasoningFor(l.id).id,l.id);assert.equal(content.evidenceFor(l.id).id,l.id);assert(g4env.store.validateRecord({...g4record,lessonId:l.id,answers:{word:{choice:l.wordAnswer,attempts:1,hinted:false},meaning:{choice:l.answer,attempts:1,hinted:false},evidence:{choice:l.evidenceAnswer,attempts:1,hinted:false},reasoning:{choice:l.reasoningAnswer,attempts:1,hinted:false}}}))}
assert.equal(content.minimumWords('g3-notebook'),20);assert.equal(content.reasoningFor('g3-notebook'),undefined);
console.log('PASS: 16 Grade 4 lessons; evidence and reasoning required; 40-word participation rule; earlier rules unchanged; mixed-course backups preserve paragraphs, hints, attempts; invalid reasoning restore leaves work unchanged.');

const g5env=setup();const author=g5env.store.addProfile('Thoughtful Author','5').activeId;const g5l=content.gradeFiveLessons[0];
const g5record={lessonId:g5l.id,step:4,completed:true,draft:'The observatory records suggest that visitors needed clearer instructions rather than an immediate telescope repair. A useful next step is to test a new instruction card beside the instrument.\n\nSource A describes repeated explanations about the focusing knob. Source B reports successful equipment checks and a missing instruction card. Together, the sources support an instruction problem, although neither proves that a new card will solve it.\n\nI recommend trying a clear card and recording whether visitors still need the same explanations. The next session can provide evidence about whether the change helps.',sourceNotes:{A:'Visitors repeatedly needed focus explanations. Only one volunteer’s shift is described.',B:'Equipment checks passed; instruction card was missing. New card not tested yet.'},answers:{word:{choice:g5l.wordAnswer,attempts:1,hinted:false},meaning:{choice:g5l.answer,attempts:1,hinted:false},evidence:{choice:g5l.evidenceAnswer,attempts:2,hinted:true},reasoning:{choice:g5l.reasoningAnswer,attempts:1,hinted:false}}};
assert(g5env.store.validateRecord(g5record));assert(!g5env.store.validateRecord({...g5record,draft:Array(59).fill('word').join(' ')}));assert(g5env.store.validateRecord({...g5record,draft:Array(60).fill('word').join(' ')}));
const g5missing=structuredClone(g5record);delete g5missing.answers.reasoning;assert(!g5env.store.validateRecord(g5missing));
for(const badNotes of [{C:'Not a source in this lesson'},{A:22},{A:'x'.repeat(501)},['note'],null,JSON.parse('{"__proto__":"not a source"}')])assert(!g5env.store.validateRecord({...g5record,sourceNotes:badNotes}));
assert(!g5env.store.validateRecord({...g4record,sourceNotes:{A:'Not supported in this older course'}}));
assert(g5env.store.validateRecord({...g5record,sourceNotes:undefined})); // Notes are optional.
const onlyNotes={...content.emptyRecord(g5l.id),step:3,sourceNotes:{A:'Useful first note'}};assert(g5env.store.validateRecord(onlyNotes));assert(!g5env.store.validateRecord({...onlyNotes,step:4,completed:true})); // Notes never replace a report.
assert(content.hasWritingChanges(onlyNotes,content.emptyRecord(g5l.id)));assert(!content.hasWritingChanges(onlyNotes,onlyNotes));assert(!content.hasWritingChanges({...g5record,sourceNotes:{B:'b',A:'a'}},{...g5record,sourceNotes:{A:'a',B:'b'}}));assert(content.hasWritingChanges({...g5record,sourceNotes:{}},g5record));
g5env.store.saveProgress(onlyNotes,author);assert.equal(g5env.store.loadProgress(author)[g5l.id].sourceNotes.A,'Useful first note');
for(const record of [old,krecord,g3record,g4record,g5record])g5env.store.saveProgress(record,author);
for(const grade of ['K','1','2','3','4','5']){g5env.store.saveGrade(grade,author);assert.equal(content.courseLessons(grade).filter(l=>g5env.store.loadProgress(author)[l.id]?.completed).length,1)}
const g5backup=g5env.store.createBackup();const g5restore=setup().store.restoreBackup(g5backup).profiles.find(p=>p.grade==='5');assert(g5restore);assert.equal(Object.keys(g5restore.records).length,5);assert.equal(JSON.stringify(g5restore.records[g5l.id].sourceNotes),JSON.stringify(g5record.sourceNotes));assert.equal(g5restore.records[g5l.id].draft,g5record.draft);
const noteTamper=structuredClone(g5backup);noteTamper.profiles.find(p=>p.grade==='5').records[g5l.id].sourceNotes.Z='unknown';const beforeNotes=JSON.stringify(g5env.store.loadWorkspace());assert.throws(()=>g5env.store.restoreBackup(noteTamper));assert.equal(JSON.stringify(g5env.store.loadWorkspace()),beforeNotes);
const failingNotes=setup();failingNotes.store.saveProgress(g5record);const beforeQuotaNotes=JSON.stringify(failingNotes.store.loadWorkspace());failingNotes.block();assert.throws(()=>failingNotes.store.saveProgress({...g5record,sourceNotes:{A:'Should not replace the saved note'}}));assert.equal(JSON.stringify(failingNotes.store.loadWorkspace()),beforeQuotaNotes);
for(const l of content.gradeFiveLessons){assert.equal(l.text.length,4);assert(content.wordCount(l.text.join(' '))>=200);assert(l.sources.length>=2&&l.sources.length<=3);assert.equal(new Set(l.sources.map(s=>s.id)).size,l.sources.length);for(const options of [l.wordOptions,l.options,l.evidenceOptions,l.reasoningOptions])assert.equal(options.length,3);for(const a of [l.wordAnswer,l.answer,l.evidenceAnswer,l.reasoningAnswer])assert(Number.isInteger(a)&&a>=0&&a<=2);assert.equal(content.minimumWords(l.id),60);assert(g5env.store.validateRecord({...g5record,lessonId:l.id,answers:{word:{choice:l.wordAnswer,attempts:1,hinted:false},meaning:{choice:l.answer,attempts:1,hinted:false},evidence:{choice:l.evidenceAnswer,attempts:1,hinted:false},reasoning:{choice:l.reasoningAnswer,attempts:1,hinted:false}},sourceNotes:Object.fromEntries(l.sources.map(s=>[s.id,'A note from '+s.title]))}))}
assert.deepEqual(['k-rhyme','beavers','g3-notebook','g4-map-room','g5-observatory'].map(content.minimumWords),[1,6,20,40,60]);
console.log('PASS: Grade 5 source sets, required evidence/reasoning, 60-word report threshold; optional per-source notes validate, save, restore and trigger unsaved detection; quota failure preserves notes; earlier courses unchanged.');
